/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseFinish();
		
		public void raisePurple();
		
		public void raiseYellow();
		
		public long getPurpleTime();
		
		public void setPurpleTime(long value);
		
		public long getYellowTime();
		
		public void setYellowTime(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
